### ISSUE TITLE
ChatGPT, GPT-3 and related stuff

### ISSUE THREAD

**Issue by momobobe** [you-apps/TranslateYou#169]
### General informations

I have tested ChatGPT for fun and surprisingly found its ability of translation is among the top level (as good as DeepL or even better, far superior than Google Translate). It sounds like using a sledgehammer to crack a nut, but I think we can have a try as there's no harm and it may even attract more users to this app.

### API basic informations

- [X] This translation engine requires a registered account.
- [X] This translation engine requires an free api key.
- [X] This translation engine requires an paid api key.

### Translation engine api key

unfortunately there is a matching mechanism that a token must be used from the same ip address as generated

### Details and links

There is no official APIs for ChatGPT right now, but you can find a lot of unofficial ones. Please feel free to explore below:

- https://github.com/eon01/awesome-chatgpt
- https://github.com/jqueryscript/ChatGPT

or search in your style

The company, OpenAI, however, provides official APIs for GPT-3, which is an earlier version, while ChatGPT is also known as GPT-3.5. As I tested, it provides very similar performance to ChatGPT in the aspect of translation. For documents, please visit https://platform.openai.com/docs/introduction

Before registration at OpenAI, you may want to play with the AI for a while. Fortunately, there are quite a few sites providing access to the service as proxy:

- https://chat-gpt-alpha.vercel.app/ (source at https://github.com/nisabmohd/ChatGPT, easy signup)
- https://www.teach-anything.com/ (source at https://github.com/lvwzhen/teach-anything, no signup)

To make a translation, casually add commands in natural language like "translate the following text into [language]" or anything similar before the text.

Many Android demo apps working with ChatGPT or GPT-3 are also available on GitHub.

Bonus: Microsoft's Bing is deploying their version called Sydney, powered by the same technology, and maybe you'd have a look at https://github.com/PawanOsman/sydney-ai or https://github.com/acheong08/EdgeGPT if interested.

### Acknowledgements

- [X] I have searched the existing requests and this is a new ticket, NOT a duplicate or related to another open or closed request.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by yhm3ps1jfp76nkd** [comment]
Also there is https://github.com/Chamidilshan/ChatGPT-App

**Comment by Bnyro** [comment]
Sorry for noy getting any response for a while, I saw the issue during my vacation and forgot to answer afterwards.

I have some concerns about adding ChatGPT at the current state, I'll explain the reasons below:
* Supported languages: Contrary to other translation engines, ChatGPT probably doesn't have any list of supported languages, which could be used for language selection. Even if there was one, the quality of translations would probably depend a lot on the selected languages because the datasets it got trained with probably were mostly English, so other less spoken languages might be unusable (not tested).
* ~There only are revered but no official APIs, so they might be unstable or subject to change.~ It seems like OpenAI published an official API today but I didn't yet have time to look at it.
*  I myself am not a fan of OpenAI, so I don't want to use or depend on their services (which is irrelevant for the issue, however)

For those reasons, at the moment, I don't plan adding GPT support myself. However, that might change in the future depending how the CahtGPT API and everything goes, so I will leave the issue open for now.

**Comment by soyelmismo** [comment]
> can also spy contents in your phone
wtf

yo, just here to recommend that the api endpoint can be changed as well as the api key, theres a lot of mirrors for this apis so... yes. its a good free practice lol

**Comment by Bnyro** [comment]
We won't use GPT directly within the app, but we'll rather use more machine learning translation engines such as Apertium instead, as these were made to server the purpose of a translator app.
