### ISSUE TITLE
Tess Improvements

### ISSUE THREAD

**Issue by Doomsdayrs** [you-apps/TranslateYou#280]
### Describe your suggested feature

The tess dialog is claustrophobic and close to bare metal.

Improving the dialog can help make it easier to understand what to do.

- [ ] Tess Screen instead of a dialog
  - [ ] Easy link to https://github.com/tesseract-ocr/tessdata
  - [ ] Description of what Tess is
- [ ] Flesh out Tess data object
  - [ ] Sizes

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by drogga** [comment]
@Bnyro
The `Translation from Image` doesn't have any search filter, or at least that's the case on A.8 x86 1440x900 rez., _also the UI isn't really scrollable with a mouse cursor, but with the scroll wheel and IDK if that's Material You/v3 or whatever issue or this app's_.

_I don't think that it was necessary to create new issue ticket(s) for this, hence I posted it here, since it's related, but if my comment is problematic, them please let me know and I will delete it - NP_ ;)

**Comment by Bnyro** [comment]
I don't really think a search feature makes much sense here?

The filenames are the ones from https://github.com/tesseract-ocr/tessdata - I don't think there's a gppd way to get the language names from these filenames.

**Comment by drogga** [comment]
Hence a search filter would be extremely helpful and is needed (since the first line is with a question mark)...

**Comment by Bnyro** [comment]
Fair enough, please open a new issue for the search function so that it won't be forgotten.

**Comment by drogga** [comment]
Can you please do it ?
Should there be ones for the data DL and mouse scroll by dragging ?

**Comment by Bnyro** [comment]
> Can you please do it ?
>
You're the one asking for improvements here, I don't :shrug:

> Should there be ones for the data DL and mouse scroll by dragging ?
>
For the data dl yes, for mouse scroll no: None of the You Apps supports mouse or keyboard inputs or aims to.

**Comment by drogga** [comment]
OK, I tend to not open issues in repos (have my reasons), but will create at least one for the search probably tomorrow, even tho by that time someone can implement it, since it's a basic thing, which will probably take a few minutes to implement.

Not supporting such a basic thing as navigating with a cursor is a big minus, because it's nothing special, almost all other apps that I've used are fully operational with a cursor (aka. non-touchscreen devices), except InstallWithOptions, it's nothing special or fancy, I can and people do use phones, tablets, TVs and whatever runs any OS, not just android with peripherals, being USB (OTG) or BT ones, Samsung DEX (and alternatives by other companies) is mostly used with such, but I won't be creating an issue ticket for this, because it seems that you are not interested and by the looks of it, I doubt someone else will work on it and unfortunately I can't code.
Thank You for everything. Bye for now.
