### ISSUE TITLE
Translation from Image: download of tesseract-data languages is limited by window height

### ISSUE THREAD

**Issue by Retardium** [you-apps/TranslateYou#360]
### Steps to reproduce

Try to install all OCR languages libraries. 
Please watch the attached screen recording.
https://cloud.upbox.org/s/HAwywrMagYB4poA

### Expected behavior

I should be able to download more languages.

### Actual behavior

The number of installable languages is limited by the window height / resolution.

### Translate You version

7.0

### Android version

13

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by Bnyro** [comment]
The video is not available and I can't reproduce the issue.

**Comment by drogga** [comment]
I'm about to test v10, but given that I didn't see any commits particularly mentioning to fix this and if I'm not wrong @Bnyro I think that this should be ReOpened and fixed...

**Comment by drogga** [comment]
I didn't see any commits between v9.0 and 10.0 particularly mentioning to fix/change this and if I'm not wrong @Bnyro I think that this should be ReOpened and fixed, because on 3 devices I don't even see this list of downloaded data, instead the DLed langs. disappear from the list for me, unless I do a search, then they show up (with a trash button, instead of a DL one). The UI needs a lot of work.
