### ISSUE TITLE
Landscape orientation support

### ISSUE THREAD

**Issue by spidikot** [you-apps/TranslateYou#402]
### Describe your suggested feature

Well, its kind of obvious without much explanation, it would be nice to have the app support landscape screen orientation, and not only portrait.

### Other details

Im using a tablet, for me and other tablet users it's really uncomfortable, when certain apps only usd portrait screen orientation. Some tablets have a built-in feature which allows you use such apps, but it makes the "window" of the app itself very small, and the feature itself is often broken and have a lot of bugs. So it would be nice if landscape orientstion would be added. (Im not a native English speaker, so yeah. I guess you got the main idea.)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by drogga** [comment]
It actually does support Landscape orientation, but only on A.8.1 x86 (odd) and unfortunately not on phones (IDK about tablets or other devices), must be the DPI, Rez. or the fact that it's live booted on an actual PC hardware that making it show in landscape by default (nice), I hope it will finally be added ASAP and the pop-up dialogs and menus self adjust to the screen size/DPI, because on small screens I have to scroll down to see the translated text in portrait and when I force it to landscape - I can't even do this, which renders it unusable with terrible UX in those scenarios. Also there's a lot of unnecessarily blank spaces, especially in the translation pop-up dialog, I ask why ?, please reduce the spacing and make the texts, buttons, etc. more edge to edge. Thank You !

**Comment by I-I-IT** [comment]
The new pop-up is nice, since you don't have to hit return and fixes other issues. However, as other have reported, it is completely broken on landscape.mode.

![Screenshot_20240718_164855_Translate You](https://github.com/user-attachments/assets/b784dc4a-4057-4e6c-ba85-e0cf7940c8a8)
