### ISSUE TITLE
Issue when sharing text to be translated

### ISSUE THREAD

**Issue by I-I-IT** [you-apps/TranslateYou#425]
### Steps to reproduce

1. Select a sentence you want to translate
2. Click Translate (with Translate You logo)
3.

### Expected behavior

The selected text is displayed and translated

### Actual behavior

Only the text from the previous translation is displayed.

### Translate You version

9.0

### Android version

14

### Other details

This behaviour is not constant, and it will works 80% of the time fine.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I will fill out all of the requested information in this form.

**Comment by natarslan** [comment]
Im having the same issue. In my case after selecting text and clicking translate i either get
- the previous translation
- empty translation page

Android version: 14

**Comment by TechFanTheo** [comment]
Just want to add that I noticed that this only happens when Android detects a text to be translated, not when you just share the text to the app. When you are in app, and use the Translate function a lot, you will end up with a lot of "tabs" (when you click return, it will display the previous translation tab). I also noticed that the bug stems from the text seemingly not being shared with the app, although it deserve more investigation. To be clear, this issue will mainly happen when you use the translation a lot in a short time.

**Comment by natarslan** [comment]
Hmm. Im not sure if we have the same issue. My steps:

- Im in a Swedish news app in android. 
- Select text to translate
- Click translate button
- New screen pop up with translation

Until here everything is fine.

- Dont close the translate you app 
- Swith to previous app and continue reading
- Select another text, press translate
- Translate you pops up but with the previous translation

So in my case I have to close the app after each translation for it to work. 

If this is not the issue you are experiencing I can ooen a new issue (and in that case sorry for misunderstanding).

**Comment by I-I-IT** [comment]
> have seen someone requesting a pop up mini window like google translate. Maybe that can be a solution to what Im describing (

Since this is now implemented, I can consider this issue as closed.
